# 登录 shell，加载文件 /etc/profile
# 上述文件加载后将到用户 HOME 目录下按顺序读取
# .bash_profile
# .bash_login
# .profile
# 只读第一个文件

if [[ -d "$HOME/bin" ]]; then
    echo "添加PATH $HOME/bin"
    PATH=$HOME/bin:$PATH
fi

if [[ -d "$HOME/.rvm/bin" ]]; then
    echo "添加PATH $HOME/.rvm/bin"
    PATH=$HOME/.rvm/bin:$PATH
fi

if [[ -d "/usr/local/bin" ]]; then
    echo "添加PATH /usr/local/bin"
    PATH=/usr/local/bin:$PATH
fi

export ANDROID_SDK=$HOME/Library/Android/sdk
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

export PATH

