# 非登录 shell 加载此文件

# node version manager
if [[ -d ~/.nvm ]]; then
    export NVM_DIR="$HOME/.nvm"
    source "$NVM_DIR/bash_completion"
    source "$NVM_DIR/nvm.sh"
fi

# python version manager
if [[ -d ~/.pyenv ]]; then
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init --path)"
fi

# android studio sdk
if [[ -d ~/Library/Android/sdk ]]; then
    export ANDROID_SDK=$HOME/Library/Android/sdk
    export ANDROID_HOME=$HOME/Library/Android/sdk
    export PATH=$PATH:$ANDROID_HOME/emulator
    export PATH=$PATH:$ANDROID_HOME/tools
    export PATH=$PATH:$ANDROID_HOME/tools/bin
    export PATH=$PATH:$ANDROID_HOME/platform-tools
fi

if [[ -d /Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home ]]; then
    export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home
    export CLASSPATH=$JAVA_HOME/lib/tools.jar:$JAVA_HOME/lib/dt.jar
    export PATH=$JAVA_HOME/bin:$PATH
fi

echo "Loaded bashrc"
# . "$HOME/.cargo/env"
