
[[ -r "$HOME/.bashrc" ]] && source "$HOME/.bashrc"

[[ -r "$HOME/.bash_profile" ]] && source "$HOME/.bash_profile"

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
export MANPATH=/usr/local/man
export EDITOR=vim

export ZSH=$HOME/.oh-my-zsh

# 主题设置，更多主题查看 ~/.oh-my-zsh/themes/，随机主题设置 "random"
ZSH_THEME="agnoster"
# ZSH_THEME="bullet-train"
# ZSH_THEME="pure"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="false"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
# plugins=(git brew bundle gem osx rails ruby rvm)

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# handy keybindings
# bindkey "^A" beginning-of-line
# bindkey "^E" end-of-line

alias reload="source $HOME/.zshrc"
alias zshconfig="vim ~/.zshrc"
alias ohmyzsh="subl ~/.oh-my-zsh"
alias subl="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"
alias gs="git status"
alias gb="git branch"
alias gba="git branch -a"
alias ga="git add"
alias gc="git commit -m"
alias gch="git checkout"
# alias glog="git log --pretty=oneline"
alias glog="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --"
alias gpull="git pull --rebase upstream"
alias grebase="git rebase"
alias gpush="git push origin"
alias gcontinue="git rebase --continue"
alias gabort="git rebase --abort"
alias clr="clear"
alias ll="ls -alh"
alias rs="rails s"
alias rc="rails c"
alias cdbike="cd ~/Bestapp/bike-ticket/"
alias cdeasytally="cd /Users/luhaozhao/MyProjects/MyGits/easytally"
alias cddotfiles="cd /Users/luhaozhao/Dropbox/dotfiles"

DEFAULT_USER="luhaozhao"
source $ZSH/oh-my-zsh.sh

export NVM_DIR="/Users/luhaozhao/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
